### ISSUE TITLE
Error deploying an instance of Cluster-Logging regarding ES SearchGuard

### ISSUE THREAD

**Issue by jparrill** [openshift/cluster-logging-operator#347]
The error that I've faced is regarding an ElasticSearch one with SearchGuard, cannot be initialized and the cluster stays on RED and does not self recover: 

- Context:
```
OCP 4.4
OCS 4.3
ELO 4.4
CLO 4.4
``` 

- Fluentd
```
2020-01-28 09:12:02 +0000 [warn]: [retry_clo_default_output_es] Could not communicate to Elasticsearch, resetting connection and trying again. Connection refused - connect(2) for 172.30.166.250:9200 (Errno::ECONNREFUSED)
2020-01-28 09:12:02 +0000 [warn]: [retry_clo_default_output_es] Remaining retry: 14. Retry to communicate after 2 second(s).
2020-01-28 09:12:07 +0000 [warn]: [retry_clo_default_output_es] Could not communicate to Elasticsearch, resetting connection and trying again. Connection refused - connect(2) for 172.30.166.250:9200 (Errno::ECONNREFUSED)
2020-01-28 09:12:07 +0000 [warn]: [retry_clo_default_output_es] Remaining retry: 13. Retry to communicate after 4 second(s).
2020-01-28 09:12:16 +0000 [warn]: [retry_clo_default_output_es] Could not communicate to Elasticsearch, resetting connection and trying again. Connection refused - connect(2) for 172.30.166.250:9200 (Errno::ECONNREFUSED)
2020-01-28 09:12:16 +0000 [warn]: [retry_clo_default_output_es] Remaining retry: 12. Retry to communicate after 8 second(s).
2020-01-28 09:12:33 +0000 [warn]: [retry_clo_default_output_es] Could not communicate to Elasticsearch, resetting connection and trying again. Connection refused - connect(2) for 172.30.166.250:9200 (Errno::ECONNREFUSED)
2020-01-28 09:12:33 +0000 [warn]: [retry_clo_default_output_es] Remaining retry: 11. Retry to communicate after 16 second(s).
2020-01-28 09:13:05 +0000 [warn]: [retry_clo_default_output_es] Could not communicate to Elasticsearch, resetting connection and trying again. Connection refused - connect(2) for 172.30.166.250:9200 (Errno::ECONNREFUSED)
2020-01-28 09:13:05 +0000 [warn]: [retry_clo_default_output_es] Remaining retry: 10. Retry to communicate after 32 second(s).
2020-01-28 09:14:10 +0000 [warn]: [retry_clo_default_output_es] Could not communicate to Elasticsearch, resetting connection and trying again. Connection refused - connect(2) for 172.30.166.250:9200 (Errno::ECONNREFUSED)
2020-01-28 09:14:10 +0000 [warn]: [retry_clo_default_output_es] Remaining retry: 9. Retry to communicate after 64 second(s).
2020-01-28 09:14:15 +0000 [error]: unexpected error error_class=Elasticsearch::Transport::Transport::Errors::ServiceUnavailable error="[503] Search Guard not initialized (SG11). See https://github.com/floragunncom/search-guard-docs/blob/master/sgadmin.md"
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/elasticsearch-transport-7.4.0/lib/elasticsearch/transport/client.rb:152:in `perform_request'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/elasticsearch-api-7.4.0/lib/elasticsearch/api/actions/info.rb:19:in `info'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-elasticsearch-3.7.1/lib/fluent/plugin/out_elasticsearch.rb:394:in `detect_es_major_version'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-elasticsearch-3.7.1/lib/fluent/plugin/out_elasticsearch.rb:264:in `block in configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-elasticsearch-3.7.1/lib/fluent/plugin/elasticsearch_index_template.rb:35:in `retry_operate'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-elasticsearch-3.7.1/lib/fluent/plugin/out_elasticsearch.rb:263:in `configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin.rb:164:in `configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/multi_output.rb:74:in `block in configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/multi_output.rb:63:in `each'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/multi_output.rb:63:in `configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin/out_copy.rb:36:in `configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/plugin.rb:164:in `configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/agent.rb:130:in `add_match'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/agent.rb:72:in `block in configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/agent.rb:64:in `each'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/agent.rb:64:in `configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/label.rb:31:in `configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:147:in `block in configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:147:in `each'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/root_agent.rb:147:in `configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/engine.rb:131:in `configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/engine.rb:96:in `run_configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:812:in `run_configure'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:558:in `block in run_worker'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:741:in `main_process'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/supervisor.rb:554:in `run_worker'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/lib/fluent/command/fluentd.rb:330:in `<top (required)>'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.7.4/bin/fluentd:8:in `<top (required)>'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/bin/fluentd:23:in `load'
  2020-01-28 09:14:15 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/bin/fluentd:23:in `<main>'
```

On ElasticSearch I see that the cluster is in RED state but appears as Running and Ready on Openshift:
```
NAME                                                                READY      STATUS             RESTARTS   AGE
cluster-logging-operator-667799d786-z4nkh	          1/1     Running            0          40m
elasticsearch-cdm-nwjeo1ix-1-68855bd9b-qr6d4     2/2     Running            0          36m
elasticsearch-cdm-nwjeo1ix-2-5f5866dd47-hjwfg     2/2     Running            0          36m
elasticsearch-cdm-nwjeo1ix-3-7c75876bd4-7zpc6   2/2     Running            0          36m
fluentd-58g69                                                            0/1     CrashLoopBackOff   7          13m
fluentd-c77vw                                                            0/1     CrashLoopBackOff   7          13m
fluentd-ljwxz                                                               0/1     CrashLoopBackOff   7          13m
fluentd-v7tgt                                                               0/1     CrashLoopBackOff   7          13m
fluentd-v7tgt-debug                                                    1/1     Running            0          10m
kibana-69c75d9cd9-lcljp                                             2/2     Running            0          36m
```

This is the first time that you deploys an instance, when you kills Fluentd pods, it will be in the same status, the real error is in ElasticSearch, for any reason cannot initialize SearchGuard.

To workaround the error, you just need to delete the ELS pods and with time the cluster will reach the Green state:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2020-01-28 10:33:50,205][INFO ][container.run            ] Elasticsearch is ready and listening
/usr/share/elasticsearch/init ~
[2020-01-28 10:33:50,211][INFO ][container.run            ] Starting init script: 0001-jaeger
[2020-01-28 10:33:50,213][INFO ][container.run            ] Completed init script: 0001-jaeger
[2020-01-28 10:33:50,251][INFO ][container.run            ] Forcing the seeding of ACL documents
[2020-01-28 10:33:50,254][INFO ][container.run            ] Seeding the searchguard ACL index.  Will wait up to 604800 seconds.
[2020-01-28 10:33:50,286][INFO ][container.run            ] Seeding the searchguard ACL index.  Will wait up to 604800 seconds.
/etc/elasticsearch /usr/share/elasticsearch/init
Search Guard Admin v5
Will connect to localhost:9300 ... done
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
Elasticsearch Version: 5.6.16
Search Guard Version: <unknown>
Contacting elasticsearch cluster 'elasticsearch' ...
Clustername: elasticsearch
Clusterstate: RED
Number of nodes: 3
Number of data nodes: 3
.searchguard index already exists, so we do not need to create one.
ERR: .searchguard index state is RED.
Populate config from /opt/app-root/src/sgconfig/
Will update 'config' with /opt/app-root/src/sgconfig/sg_config.yml
   SUCC: Configuration for 'config' created or updated
Will update 'roles' with /opt/app-root/src/sgconfig/sg_roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update 'rolesmapping' with /opt/app-root/src/sgconfig/sg_roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'internalusers' with /opt/app-root/src/sgconfig/sg_internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update 'actiongroups' with /opt/app-root/src/sgconfig/sg_action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
Done with success
/usr/share/elasticsearch/init
[2020-01-28 10:34:25,709][INFO ][container.run            ] Seeded the searchguard ACL index
[2020-01-28 10:34:25,710][INFO ][container.run            ] Disabling auto replication
/etc/elasticsearch /usr/share/elasticsearch/init
Search Guard Admin v5
Will connect to localhost:9300 ... done
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
Elasticsearch Version: 5.6.16
Search Guard Version: <unknown>
Reload config on all nodes
Auto-expand replicas disabled
/usr/share/elasticsearch/init
[2020-01-28 10:34:39,568][INFO ][container.run            ] Updating replica count to 1
/etc/elasticsearch /usr/share/elasticsearch/init
Search Guard Admin v5
Will connect to localhost:9300 ... done
ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
...
...
```

- After kill ELS pods and waiting a bit you could see in the ELS logs this entry which seems that the recovery happens:
```
Elasticsearch Version: 5.6.16
Search Guard Version: <unknown>
Reload config on all nodes
Update number of replicas to 1 with result: true
/usr/share/elasticsearch/init
[2020-01-28 10:34:45,420][INFO ][container.run            ] Adding index templates
[2020-01-28 10:34:45,608][INFO ][container.run            ] Index template 'com.redhat.viaq-openshift-operations.template.json' found in the cluster, overriding it
{"acknowledged":true}[2020-01-28 10:35:15,288][INFO ][container.run            ] Index template 'com.redhat.viaq-openshift-orphaned.template.json' found in the cluster, overriding it
{"acknowledged":true}[2020-01-28 10:35:45,330][INFO ][container.run            ] Index template 'com.redhat.viaq-openshift-project.template.json' found in the cluster, overriding it
{"acknowledged":true}[2020-01-28 10:35:50,283][INFO ][container.run            ] Index template 'common.settings.kibana.template.json' found in the cluster, overriding it
{"acknowledged":true}[2020-01-28 10:36:00,286][INFO ][container.run            ] Index template 'common.settings.operations.orphaned.json' found in the cluster, overriding it
{"acknowledged":true}[2020-01-28 10:36:00,585][INFO ][container.run            ] Index template 'common.settings.operations.template.json' found in the cluster, overriding it
{"acknowledged":true}[2020-01-28 10:36:00,868][INFO ][container.run            ] Index template 'common.settings.project.template.json' found in the cluster, overriding it
{"acknowledged":true}[2020-01-28 10:36:01,151][INFO ][container.run            ] Index template 'jaeger-service.json' found in the cluster, overriding it
{"acknowledged":true}[2020-01-28 10:36:01,435][INFO ][container.run            ] Index template 'jaeger-span.json' found in the cluster, overriding it
{"acknowledged":true}[2020-01-28 10:36:01,729][INFO ][container.run            ] Index template 'org.ovirt.viaq-collectd.template.json' found in the cluster, overriding it
{"acknowledged":true}[2020-01-28 10:36:01,935][INFO ][container.run            ] Finished adding index templates
[2020-01-28 10:36:01,940][INFO ][container.run            ] Starting init script: 0500-remove-index-patterns-without-uid
[2020-01-28 10:36:02,090][INFO ][container.run            ] Found 0 index-patterns to evaluate for removal
[2020-01-28 10:36:02,090][INFO ][container.run            ] Completed init script: 0500-remove-index-patterns-without-uid with 0 successful and 0 failed bulk requests
[2020-01-28 10:36:02,094][INFO ][container.run            ] Starting init script: 0510-bz1656086-remove-index-patterns-with-bad-title
[2020-01-28 10:36:02,255][INFO ][container.run            ] Found 0 index-patterns to remove
[2020-01-28 10:36:02,441][INFO ][container.run            ] Completed init script: 0510-bz1656086-remove-index-patterns-with-bad-title
[2020-01-28 10:36:02,446][INFO ][container.run            ] Starting init script: 0520-bz1658632-remove-old-sg-indices
[2020-01-28 10:36:02,740][WARN ][container.run            ] Found .searchguard setting 'index.routing.allocation.include._name' to be null
[2020-01-28 10:36:02,741][INFO ][container.run            ] Updating .searchguard setting 'index.routing.allocation.include._name' to be null
[2020-01-28 10:36:02,899][INFO ][container.run            ] Completed init script: 0520-bz1658632-remove-old-sg-indices
[2020-01-28 10:36:02,903][INFO ][container.run            ] Starting init script: 0530-bz1667801-fix-kibana-replica-shards
[2020-01-28 10:36:03,042][INFO ][container.run            ] Found 0 Kibana indices with replica count not equal to 1
[2020-01-28 10:36:03,042][INFO ][container.run            ] Completed init script: 0530-bz1667801-fix-kibana-replica-shards

```

**Comment by jcantrill** [comment]
@jparrill what images are being used here?

Try removing the SG index
`oc exec -c elasticsearch $espod -- es_util --query=/.searchguard -XDELETE`

 and reinitializing:

`oc exec -c elasticsearch $espod -- es_seed_acl`

**Comment by jparrill** [comment]
Concretely in this case:

```
openshift-ose-oauth-proxy@sha256:4953a08fbedecdd1b383ba8a8cf0d34240d5c3fc56c57264dee5e7dfb7189c63
```

I've already figured out how to solve it :/ and it's workarounded but I didn't know the real problem that is under the hood. I will try to reproduce it again and I will try to execute these commands, thanks @jcantrill

**Comment by mustafakaya** [comment]
@jparrill I'm getting the same error, how did you solve that?  Thanks.

**Comment by mustafakaya** [comment]
Hi @jcantrill , I tried to delete and reinitialize SG index but I got the following error. Thanks.

> oc exec -c elasticsearch elasticsearch-cdm-85u334ts-1-5dd99bb9-vrlrn -- es_util --query=/.searchguard -XDELETE
> 
> No handler found for uri [//.searchguard] and method [DELETE]

**Comment by Sispheor** [comment]
I had the same issue on my Openshift 4.4 cluster after a full restart. I just deleted all ELS and fluentd pods and it worked. Thanks for the workaround.

**Comment by nitinanjankar** [comment]
I had a similar issue on my Openshift 4.4.3 cluster. I have only deleted all ELS and fluentd pods and all of my fluentd and ES pods came in Running state.

But I noticed that still the metrics endpoint for target in ERROR state.
Get https://xx.xx.xxx.xx:24231/metrics: dial tcp xx.xx.xxx.xx:24231: connect: connection refused

**Comment by jcantrill** [comment]
> Hi @jcantrill , I tried to delete and reinitialize SG index but I got the following error. Thanks.
> 
> > oc exec -c elasticsearch elasticsearch-cdm-85u334ts-1-5dd99bb9-vrlrn -- es_util --query=/.searchguard -XDELETE
> > No handler found for uri [//.searchguard] and method [DELETE]

Minor typo in my command. it should be:

```
oc exec -c elasticsearch $pod -- es_util --query=.searchguard -XDELETE
oc exec -c elasticsearch $pod -- es_seed_acl
```
